- .codecov.yml
- .github/workflows/build.yaml
- .gitignore
- Makefile
> Add codecov integration, sample YAML config

- README.md
- github/auth.go
- github/client_repositories_org.go
- github/client_repositories_user.go
- github/client_repository_deploykey.go
- github/client_repository_teamaccess.go
- github/example_organization_test.go
- github/example_repository_test.go
- github/resource_teamaccess.go
- gitprovider/client.go
- gitprovider/gitprovider.go
- gitprovider/resources.go
And some examples as per https://blog.golang.org/examples
cc @dinosk @twelho please review
> Add user documentation

- github/auth.go
- github/client.go
And a statement that was wrong, as spotted by @michaelbeaumont :+1:
> Fix github.Client.Raw() return value

- .github/workflows/goreleaser.yaml
- .goreleaser.yml
cc @twelho @stefanprodan reduces some of our work :smile:
> Generate release notes with goreleaser automatically

- github/auth.go
See https://github.com/weaveworks/eksctl/pull/2561#discussion_r474129903
> Add TokenVariable to github

- .github/workflows/rebase.yaml
This action allows contributors to rebase PRs by commenting with `/rebase` on an opened pull request.
> Add rebase GitHub action

- gitlab/client_repositories_org.go
- gitlab/gitlabclient.go
- gitlab/integration_test.go
- gitlab/resource_repository.go
Adds AutoInit support to Gitlab so we can create repositories that come with README.md s etc.
> Adds AutoInit support to GitLab

- github/client_repository_branch.go
- github/client_repository_commit.go
- github/client_repository_pullrequest.go
- github/example_organization_test.go
- github/githubclient.go
- github/integration_test.go
- github/resource_commit.go
- github/resource_repository.go
- github/util.go
- gitlab/client_repository_branch.go
- gitlab/client_repository_commit.go
- gitlab/client_repository_pullrequest.go
- gitlab/gitlabclient.go
- gitlab/integration_test.go
- gitlab/resource_commit.go
- gitlab/resource_repository.go
- gitprovider/cache/httpcache.go
- gitprovider/client.go
- gitprovider/resources.go
- gitprovider/types_repository.go
- go.sum
Changes:
- implement create branches, pullrequests and commits
- implement listing for commits
Fix: #72
Fix: #73
> Add support for managing branches, PRs and commits

- MAINTAINERS
Updating my email address in the maintainers file
> Update contact info in MAINTAINERS file

- MAINTAINERS
> Add emeritus maintainers

- github/githubclient.go
- github/resource_commit.go
- gitlab/gitlabclient.go
- gitlab/resource_commit.go
- gitprovider/types_repository.go
adds a commit link to the commit object.
https://github.com/J-Thompson12/go-git-providers/runs/3499538968?check_suite_focus=true
> add url link to commits

- .github/workflows/lint.yaml
- revive/config.toml
Adding a linter
https://github.com/mgechev/revive
https://github.com/souleb/go-git-providers/actions/runs/1220339186
> adding a linter

- gitprovider/errors.go
This error is one I am looking for in weave gitops
> add gitlab group err

- MAINTAINERS
Add mention in the MAINTAINERS file that I am an independent contributor.
No code changes.
Signed-off-by: Dinos Kousidis <dinos.simpson@gmail.com>
> Add org affinity for dinosk

- MAINTAINERS
Signed-off-by: Dinos Kousidis <dinos.simpson@gmail.com>
Update my employer in the MAINTAINERS file
Did not change any code files.
> Update employer in MAINTAINERS file

- gitlab/util.go
Fixes #128 
Fixes wrong error message for func validateIdentityFields
[](https://github.com/fluxcd/go-git-providers/runs/4262871206?check_suite_focus=true)
> Fixes wrong error message for func validateIdentityFields

- github/integration_test.go
- gitlab/integration_test.go
- stash/integration_suite_test.go
Ref: https://github.com/fluxcd/flux2/issues/1658
> Remove deprecated `io/ioutil`

- stash/projects.go
If implemented this will guard against index out of range errors.
Related to https://github.com/fluxcd/flux2/discussions/2332
> [Stash] Return not found when project slice is empty

- .github/workflows/build.yaml
- .github/workflows/e2e.yaml
- .github/workflows/goreleaser.yaml
- DEVELOPMENT.md
Upgrading golang version to 1.18.
> Upgrade GO dependency to 1.18

- .github/workflows/scan.yaml
Scan for vulnerabilities with GitHub CodeQL
> Add CodeQL scan workflow

- DEVELOPMENT.md
Signed-off-by: Daniel Holbach <daniel@weave.works>
> update to new doc links structure

- MAINTAINERS
I'd like to become a maintainer of this repository. At the moment I'm working on adding edit functionality to the `PullRequestClient` (#165) with the plan to enhance its functionality more as part of on-going work on Weave GitOps OSS and Enterprise.
> Add Max Jonas Werner as maintainer

- github/auth.go
- github/client.go
- github/client_organization_teams.go
- github/client_repositories_org.go
- github/client_repository_branch.go
- github/client_repository_commit.go
- github/client_repository_deploykey.go
- github/client_repository_file.go
- github/client_repository_pullrequest.go
- github/example_organization_test.go
- github/example_repository_test.go
- github/githubclient.go
- github/integration_test.go
- github/resource_commit.go
- github/resource_deploykey.go
- github/resource_organization.go
- github/resource_pullrequest.go
- github/resource_repository.go
- github/util.go
- github/util_test.go
- go.mod
- go.sum
go-github to v48.2.0 and xanzy/go-gitlab to v0.77.0
> Upgrade dependencies

- github/example_organization_test.go
- github/integration_test.go
- github/resource_pullrequest.go
- gitlab/integration_test.go
- gitlab/resource_pullrequest.go
- gitprovider/types_repository.go
- stash/integration_repositories_org_test.go
- stash/integration_repositories_user_test.go
- stash/resource_pullrequest.go
Add title and description for pull requests.
Kudos to @luizbafilho for putting this together 🙏
> Add title and description for pull requests

- stash/git.go
When the `CreateCommit` function in `GitService` creates a new branch, the dirty state of the repo will be cleaned and new all files disappear.
There has to be a more developer friendlier method. I can't run tests locally without a valid GitHub, GitLab, and a Stash token.
> fix: stash empty commit

- azuredevops/client_repository_commit.go
- azuredevops/client_repository_pullrequest.go
- azuredevops/resource_commit.go
- azuredevops/resource_pullrequest.go
- azuredevops/resource_repository.go
Add support for creating commits and listing commits using Azure Devops
Add support for pull requests
related to #186
> Azure Devops 

- .github/workflows/e2e.yaml
As per https://github.com/fluxcd/go-git-providers/pull/197#issuecomment-1469998029
> build: delete all vars with no secret configured 

- DEVELOPMENT.md
https://github.com/orgs/community/discussions/16925
> docs: format note so that it's rendered nicely

- .github/dependabot.yaml
> ci: Group dependabot updates

- MAINTAINERS
Change my information in the maintainers file.
> changing Soule info

- MAINTAINERS
> Update Soule BA Affiliation

- MAINTAINERS
Retire maintainers @foot and @yiannistri due to inactivity 6+ months.
> Retire Simon and Yiannis
