fluxcd/go-git-providers

- client.go
And add an `actionTaken bool` return argument for `Reconcile()`.
Fixes: #3 
Also changes the following (also likewise for Repository)
```go
// before
ResourceClient.Organization(o OrganizationRef) OrganizationClient
// after
ResourceClient.Organization(ctx context.Context, o OrganizationRef) (OrganizationClient, *Organization, error)
```
This is has the following benefits:
- If the `OrganizationRef` that is given is invalid, or doesn't exist, an error is returned immediately, and not when calling e.g. a `OrganizationClient.Teams().List(...)` which would be rather unintuitive.
- The `*Organization` object is returned at the same time, in order to not have to do an extra `Organizations.Get(ctx, o)` resulting in two roundtrips to the server
Fixes: #6 
cc @twelho @stefanprodan
> Document the Client in a more consistent way 

- github/auth.go
- github/client_organizations.go
- github/integration_test.go
- go.mod
- go.sum
Fixes: #23 
cc @twelho @yiannistri @martina-if please review
> Implement Conditional Requests

- github/auth.go
- github/client.go
- github/client_organization_teams.go
- github/client_organizations.go
- github/client_repositories_org.go
- github/client_repositories_user.go
- github/client_repository_deploykey.go
- github/client_repository_teamaccess.go
- github/githubclient.go
- github/resource_deploykey.go
- github/resource_organization.go
- github/resource_repository.go
- github/resource_teamaccess.go
This allows us to
a) see, in a consistent way, how all API operations using `*github.Client` are done, to make sure that
- pagination works
- all returned values are validated first
- HTTP errors are handled consistently
b) later, create mock implementations of the `githubClient` interface for unit testing of the client
c) focus on high-level operations in the main clients, not Github API details or pagination/validation/error handling.
cc @twelho @dinosk please review
> Factor out a high-level githubClient interface for all operations.

- github/auth.go
- github/auth_test.go
- github/example_organization_test.go
- github/example_repository_test.go
- github/githubclient.go
- github/integration_test.go
- gitprovider/cache/httpcache.go
- gitprovider/client_options.go
- gitprovider/client_options_test.go
- gitprovider/errors.go
And code can be shared across providers.
~~Please look at only the last 3 commits, as this is besed on #26~~ **EDIT**: Now rebased and ready-to-merge.
@dinosk @twelho please review
> Restructure Options and Transport functionality to become generic

- README.md
- github/auth.go
- github/auth_test.go
- github/integration_test.go
PATs are oauth tokens so there's no reason to use BasicAuth here.
I read the GH docs as recommending `Authorization: Bearer` if possible.
GH understands what kind of token is being used, e.g. I see:
`Added on Aug 20, 2020 via personal access token owned by
@michaelbeaumont`
when I authenticate this way and add a DeployKey
I left the interface as is but `WithPersonalAccessToken` could also just be removed.
> Use Authorization header for Github PAT

- MAINTAINERS
- README.md
Since Aug 21, I'm off to my second year at Aalto University, studying [Digital Systems and Design](https://www.aalto.fi/en/study-options/aalto-bachelors-programme-in-science-and-technology-digital-systems-and-design). Hence, I am not working at the moment (probably until next summer :smile:)
Have fun folks!
> Remove Lucas from MAINTAINERS file

- github/githubclient.go
- github/integration_test.go
Checks if the `Visibility` field is set to private, and sets the `Private` flag in the request object sent to go-github.
Fix: #44
> Set private field in github repo creation

- github/client.go
- github/integration_test.go
- gitlab/client.go
- gitprovider/client.go
- gitprovider/enums.go
- gitprovider/errors.go
> Implement HasTokenPermission to ensure token has requested permission

- github/integration_test.go
The default branch in newly created github repos has been renamed from `master` to `main`. This change corrects the validation of repos in github integration tests.
When the branch name changes in other providers the value in [gitprovider/types_repository.go](https://github.com/fluxcd/go-git-providers/blob/master/gitprovider/types_repository.go#L33) can be updated too as per the related comments.
> Change default branch in github integration tests to main

- gitlab/auth.go
- gitlab/auth_test.go
- gitlab/client.go
- gitprovider/repositoryref.go
- gitprovider/repositoryref_test.go
- gitprovider/util.go
Adds utility function `GetDomainURL` to set the URL scheme of a domain to `https://`, if it is not specified. 
Closes #55
> Add util func for getting domain urls

- gitlab/integration_test.go
- gitprovider/util.go
The scheme of custom gitlab urls is parsed incorrectly in `GetDomainURL` util.
This checks specifically if it matches `http` or `https`.
```
*Gitlab*
Running Suite: GitLab Provider Suite
====================================
Random Seed: 1619706988
Will run 11 of 11 specs
GitLab Provider 
should list the available organizations the user has access to
/home/dinos/go/src/github.com/weaveworks/go-git-providers/gitlab/integration_test.go:258
[It] should list the available organizations the user has access to
/home/dinos/go/src/github.com/weaveworks/go-git-providers/gitlab/integration_test.go:258
•
------------------------------
GitLab Provider 
should not fail when .Children is called
/home/dinos/go/src/github.com/weaveworks/go-git-providers/gitlab/integration_test.go:307
[It] should not fail …
```
> Check url scheme matches http or https

- gitlab/integration_test.go
- gitprovider/testutils/key_pair.go
- go.mod
Copies `key_pair.go` from https://github.com/fluxcd/pkg/blob/main/ssh/key_pair.go to `gitprovider/testutils` to generate deploy keys in each integration test run, replacing hardcoded values.
```
➜  go-git-providers git:(generate-deploy-keys-in-tests) make test
go mod tidy
go fmt ./...
go vet ./...
go test -race -coverprofile=coverage.txt -covermode=atomic ./...
?   	github.com/fluxcd/go-git-providers/bitbucket	[no test files]
ok  	github.com/fluxcd/go-git-providers/github	13.853s	coverage: 50.4% of statements
ok  	github.com/fluxcd/go-git-providers/gitlab	44.154s	coverage: 74.0% of statements
ok  	github.com/fluxcd/go-git-providers/gitprovider	0.038s	coverage: 94.5% of statements
?   	github.com/fluxcd/go-git-providers/gitprovider/cache	[no test files]
? …
```
> Generates deploy keys in each integration test run

- gitlab/client_repository_commit.go
- go.mod
- go.sum
Updated gitlab dependency to v0.43.0
```
=== RUN   Test_clientOptions_getTransportChain
--- PASS: Test_clientOptions_getTransportChain (0.00s)
=== RUN   Test_clientOptions_getTransportChain/all_roundtrippers
--- PASS: Test_clientOptions_getTransportChain/all_roundtrippers (0.00s)
=== RUN   Test_clientOptions_getTransportChain/only_pre_+_auth
--- PASS: Test_clientOptions_getTransportChain/only_pre_+_auth (0.00s)
=== RUN   Test_clientOptions_getTransportChain/only_cache_+_auth
--- PASS: Test_clientOptions_getTransportChain/only_cache_+_auth (0.00s)
=== RUN   Test_makeOptions
--- PASS: Test_makeOptions (0.00s)
=== RUN   Test_makeOptions/no_options
--- PASS: Test_makeOptions/no_options (0.00s)
=== RUN   Test_makeOptions/WithDomain
--- PASS: Test_makeOptions/WithDomain (0.00s)
=== RUN …
```
> Updated gitlab dependency to v0.43.0

- README.md
- github/client_repository_pullrequest.go
- github/integration_test.go
- github/resource_pullrequest.go
- gitlab/client_repository_pullrequest.go
- gitlab/integration_test.go
- gitlab/resource_pullrequest.go
- gitprovider/client.go
- gitprovider/resources.go
- gitprovider/types_repository.go
- Introduced a PullRequest interface that can be used to get information about a pull request.
- Implemented interface for both GitHub and GitLab providers
- Currently it returns the (web) URL of the newly created pull request
- Updated README to document environment variables used during test runs
```bash
➜ make test
go mod tidy
go fmt ./...
go vet ./...
go test -race -coverprofile=coverage.txt -covermode=atomic ./...
?   	github.com/fluxcd/go-git-providers/bitbucket	[no test files]
ok  	github.com/fluxcd/go-git-providers/github	14.856s	coverage: 50.8% of statements
ok  	github.com/fluxcd/go-git-providers/gitlab	46.675s	coverage: 73.9% of statements
ok  	github.com/fluxcd/go-git-providers/gitprovider	0.170s	coverage: 94.5% of statements
? …
```
> Return WebURL of newly created pull request

- .github/workflows/e2e.yaml
- .github/workflows/goreleaser.yaml
- CONTRIBUTING.md
- Makefile
- README.md
- github/integration_test.go
- gitlab/integration_test.go
Changes the GITHUB_TOKEN environmental variable to GITPROVIDER_BOT_TOKEN
because github secrets cannot start with GITHUB_
Add an option to cleanup all test repos, the integration tests sometimes
fail to cleanup.
Signed-off-by: Paul Carlton <paul.carlton@weave.works>
Changes the GITHUB_TOKEN environmental variable to GITPROVIDER_BOT_TOKEN
because github secrets cannot start with GITHUB_
Add an option to cleanup all test repos, the integration tests sometimes
fail to cleanup.
go mod tidy
go fmt ./...
go vet ./...
go test  -race -coverprofile=coverage.txt -covermode=atomic ./...
?       github.com/fluxcd/go-git-providers/bitbucket    [no test files]
ok      github.com/fluxcd/go-git-providers/github       13.859s coverage: 50.8% of statements
ok      github.com/fluxcd/go-git-providers/gitlab …
> Support running tests in forked repository workflow

- github/integration_test.go
- gitlab/integration_test.go
- gitprovider/testutils/retry.go
Signed-off-by: Paul Carlton <paul.carlton@weave.works>
Added retry for failing integration test operation. Will add others as I encounter other failures
https://github.com/paulcarlton-ww/go-git-providers/runs/2895049345
> Add retries to integration tests

- github/example_repository_test.go
Please also change the website for the GH project to <https://fluxcd.io/docs>.
> update docs location

- github/example_repository_test.go
- github/githubclient.go
- github/resource_commit.go
- gitlab/gitlabclient.go
- gitlab/integration_test.go
- gitlab/resource_commit.go
- gitlab/util.go
- gitprovider/types_defaulting_test.go
- gitprovider/types_repository.go
Signed-off-by: Justin Thompson <justin@weave.works>
Added author name, commit message, and created at to CommitInfo for weave-gitops use.
https://github.com/J-Thompson12/go-git-providers/actions/runs/1113589118
> add more info to CommitInfo

- MAINTAINERS
I won't have time to help maintain, thanks all!
> Remove @michaelbeaumont from MAINTAINERS

- github/auth.go
- github/auth_test.go
- github/integration_test.go
- gitlab/auth.go
- gitlab/auth_test.go
- gitlab/integration_test.go
- gitprovider/client_options.go
- gitprovider/client_options_test.go
- go.mod
- go.sum
This work is to prepare the stash implementation.
gitlab/auth.go and github/auth.go duplicate most of their code and tests.
The code has been moved to the gitprovider pkg along with the tests.
https://github.com/souleb/go-git-providers/actions/runs/1186522224
> Refactors clientOption struct due to duplication

- .github/workflows/build.yaml
- .github/workflows/e2e.yaml
- .github/workflows/goreleaser.yaml
- go.mod
- go.sum
move from Go version 1.15 to 1.16
https://github.com/souleb/go-git-providers/runs/3535773876?check_suite_focus=true
> upgrade Go version to 1.16

- github/integration_test.go
The culprit is a test on the github test suite named
"should update if the repository already exists when reconciling"
https://github.com/souleb/go-git-providers/actions/runs/1213132680
> fix often failing e2e tests

- go-stash/client.go
- go-stash/client_test.go
- go-stash/resources.go
- go-stash/users.go
- go-stash/users_test.go
UserService permits retrieving indivudual users and listing them.
This add the client service UserService to communicate with the following rest endpoints:
/rest/api/1.0/users
/rest/api/1.0/users/{userSlug}
It is used here, in the current implementation to list and get users
A small change to http client as well to hide the dependency to retryablehttp.
https://github.com/souleb/go-git-providers/actions/runs/1220830834
https://github.com/souleb/go-git-providers/runs/3564757557?check_suite_focus=true
> [stash] Implement user service operations

- stash/client.go
- stash/client_test.go
- stash/groups.go
- stash/groups_test.go
- stash/resources.go
- stash/users.go
- stash/users_test.go
#102 
This add the client service GroupService to communicate with the following rest endpoints:
- /rest/api/1.0/admin/groups
- /rest/api/1.0/admin/groups/more-members
https://github.com/souleb/go-git-providers/runs/3587059251?check_suite_focus=true
> [Stash] This add the stash client service GroupService

- stash/client.go
- stash/client_test.go
- stash/groups.go
- stash/projects.go
- stash/projects_test.go
- stash/users.go
#102 
ProjectsService permits retrieving projects and listing them.
It permits as well retrieving a given project's users and groups with permissions.
https://github.com/souleb/go-git-providers/actions/runs/1229612646
> [Stash] adds projects service to the gostash client

- github/client_repository_pullrequest.go
- github/integration_test.go
- github/resource_pullrequest.go
- gitlab/client_repository_pullrequest.go
- gitlab/integration_test.go
- gitlab/resource_pullrequest.go
- gitprovider/client.go
- gitprovider/enums.go
- gitprovider/types_repository.go
Signed-off-by: Jerry Jackson <jrryjcksn@gmail.com>
Adds support for listing, getting, and merging pull requests in GitHub and GitLab. `Merge` and `Squash` options are supported for merge.
- Added `List()`, `Get()`, and `Merge()` operations for pull requests in `GitHub` and merge requests in `GitLab`. 
- Extended the `gitprovider.PullRequestInfo` struct to contain `Number` (id of pull request) and `Merged` (whether or not the PR has been merged)
- Added a `gitprovider.MergeMethod` enum with values for `merge` and `squash`
- Extended the integration tests to perform both merge variations for both providers
Due to GitLab's asynchronous merge status updating, the `GitLab` `Merge()` polls for MergeStatus to be updated from "checking" (up to 20 seconds) before giving up. See: …
> Add PR List, Get and Merge support for GitHub and GitLab

- gitlab/client_repository_pullrequest.go
The support for listing GitLab pull requests (merge requests) is currently using `ListMergeRequests`. This returns all merge requests accessible by the authenticated user. We should instead be using `ListProjectMergeRequests` which scopes the query to a particular project (repository).
```
arete: ~jj/go-git-providers> CGO_ENABLED=1 make test
go mod tidy
go fmt ./...
go vet ./...
go test  -race -coverprofile=coverage.txt -covermode=atomic ./...
?   	github.com/fluxcd/go-git-providers/bitbucket	[no test files]
ok  	github.com/fluxcd/go-git-providers/github	18.484s	coverage: 49.1% of statements
ok  	github.com/fluxcd/go-git-providers/gitlab	53.498s	coverage: 73.1% of statements
ok  	github.com/fluxcd/go-git-providers/gitprovider	0.038s	coverage: 92.2% of statements
? …
```
> Switch to "ListProjectMergeRequests" for GitLab

- stash/branch.go
- stash/client_repositories_org.go
- stash/client_repositories_user.go
- stash/integration_repositories_org_test.go
- stash/integration_repositories_user_test.go
- stash/repositories.go
- stash/resource_repository.go
Signed-off-by: Soule BA <bah.soule@gmail.com>
The default branch is set at repository creation time  and updated at repository update time. It is save ad a field in the repository object and can thus be used to reconcile a repository.
Stash does not provide the ability to set default branch on repository creation and update.
A separate set of api calls is provided to manage branches.
https://github.com/fluxcd/go-git-providers/runs/4035417362?check_suite_focus=true
> [Stash] Add the logic to reconcile default branch.

- go.mod
- go.sum
- stash/auth.go
- stash/client.go
- stash/client_test.go
Signed-off-by: Soule BA <bah.soule@gmail.com>
Revert log.Logger to v0.4.0 for compatibility with flux2.
There is a breaking change from log.Logger v1.0.0...
I need this for the `flux bootstrap stash`
https://github.com/fluxcd/go-git-providers/runs/4136936276?check_suite_focus=true
> [Stash] Revert log.Logger to v0.4.0 for compatibility with flux2.

- stash/auth_test.go
- stash/stash.go
Signed-off-by: Soule BA <bah.soule@gmail.com>
Fix SupportedDomain(), to make it return a host and not a full url.
https://github.com/fluxcd/go-git-providers/actions/runs/1436987613
> [Stash] Fix SupportedDomain(), to make it return a host and not a full url

- gitprovider/repositoryref.go
- gitprovider/resources.go
- stash/client_repositories_user.go
- stash/integration_repositories_org_test.go
- stash/integration_repositories_user_test.go
- stash/resource_repository.go
Signed-off-by: Soule BA <bah.soule@gmail.com>
Each provider might have its own uri/path
An interface is added for each provider to implement. The interface defines a method to generate a clone url for a specific provider.
-->](https://github.com/fluxcd/go-git-providers/actions/runs/1443790963)
> [Stash] Add methods to generate a clone url for a specific provider.

- gitlab/auth.go
- gitlab/auth_test.go
- gitlab/util.go
Fixes #135 
- Ensure that the baseURL for the gitlab client includes a scheme so that API calls succeed
- Fix validation for domain so that it uses the host part of the URL
> Ensure that the baseURL for the gitlab client includes a scheme

- .github/workflows/build.yaml
- .github/workflows/e2e.yaml
- .github/workflows/goreleaser.yaml
- go.mod
- go.sum
- stash/client.go
Upgrading to go v1.17. Also upgrading logr to V1.2 now that the others flux projects have done so.
https://github.com/fluxcd/go-git-providers/actions/runs/1663233941
> upgrade to go v1.17 and logr v1.2

- gitlab/client_repository_commit.go
- gitlab/integration_test.go
- Follow github's approach and accept `nil` to signal file deletion
Fixes #137
> Allow deleting files on gitlab

- gitlab/auth.go
- gitlab/auth_test.go
- gitlab/util.go
reverting changes of pr #136 because it break the flux bootstrap process.
https://github.com/fluxcd/flux2/issues/2284
https://github.com/fluxcd/go-git-providers/actions/runs/1688239732
> reverting pr #136

- DEVELOPMENT.md
- README.md
Documentation changes:
- add the supported Git provider APIs to the main readme
- move the test suite spec to the development doc
- mention Weaveworks as the sponsor of the Bitbucket e2e infra
> Document e2e testing and supported providers

- stash/projects.go
When fetching a project by name, a list is returned. If implented, this
will make sure we return the right project from the list.
Ref: https://github.com/fluxcd/flux2/issues/2411
(https://github.com/fluxcd/go-git-providers/runs/5157883730?check_suite_focus=true)
> [Stash] Look for the exact projectName in the returned project list

- gitlab/client_repository_deploykey.go
- gitlab/gitlabclient.go
- gitlab/resource_deploykey.go
- gitlab/util.go
- go.mod
- go.sum
This comes with some changes:
- ListSubgroupsOptions renamed to ListSubGroupsOptions
- DeployKey renamed to ProjectDeployKey
https://github.com/fluxcd/go-git-providers/runs/6992318911?check_suite_focus=true
> bump gitlab to v0.68.0

- github/auth.go
- github/client.go
- github/client_organization_teams.go
- github/client_repositories_org.go
- github/client_repository_branch.go
- github/client_repository_commit.go
- github/client_repository_deploykey.go
- github/client_repository_file.go
- github/client_repository_pullrequest.go
- github/example_organization_test.go
- github/example_repository_test.go
- github/githubclient.go
- github/integration_test.go
- github/resource_commit.go
- github/resource_deploykey.go
- github/resource_organization.go
- github/resource_pullrequest.go
- github/resource_repository.go
- github/util.go
- github/util_test.go
- go.mod
- go.sum
- stash/integration_suite_test.go
Refactor update logic for github and upgrade to v0.45.2
If implemented, we now use reflect package to dynamically create and update github repositories before reconciliation.
https://github.com/fluxcd/go-git-providers/runs/7021315747?check_suite_focus=true
> Refactor update logic for github and upgrade to go-github v0.45.2

- gitlab/integration_test.go
- gitprovider/testutils/retry.go
Still fixing the gitlab tests. This only commits a `readme` if a 404 code is return or no commit is found after a user repo is created with `autoInit`.
https://github.com/fluxcd/go-git-providers/runs/8246455467?check_suite_focus=true
> [Gitlab] do not always commit a readme as the autoInit error is not consistent

- github/integration_test.go
- github/resource_repository.go
If applied this change makes sure that all reconcile methods take into account the patched update repo.
In previous PR when refactoring to make sure github reconciliation methods do a proper patch when reconciling github repositories, we introduced a bug in the `Set()` method.
This PR update the needed code and modify the test code accordingly.
https://github.com/fluxcd/go-git-providers/actions/runs/3043540139/jobs/4902916971
> Fix github reconcile method

- github/auth.go
- github/client.go
- github/client_organization_teams.go
- github/client_repositories_org.go
- github/client_repository_branch.go
- github/client_repository_commit.go
- github/client_repository_deploykey.go
- github/client_repository_file.go
- github/client_repository_pullrequest.go
- github/example_organization_test.go
- github/example_repository_test.go
- github/githubclient.go
- github/integration_test.go
- github/resource_commit.go
- github/resource_deploykey.go
- github/resource_organization.go
- github/resource_pullrequest.go
- github/resource_repository.go
- github/util.go
- github/util_test.go
- go.mod
- go.sum
upgraging github to v47 and gitlab to v0.73.1
https://github.com/fluxcd/go-git-providers/actions/runs/3051522472/jobs/4919854218
> upgraging github to v47 and gitlab to v0.73.1

- go.mod
- go.sum
Bump go-github to v47.1.0 and go-gitlab to v0.74.0
> Bump go-github to v47.1.0 and go-gitlab to v0.74.0

- github/client_repository_file.go
- github/client_repository_pullrequest.go
- github/integration_test.go
- gitlab/client_repositories_org.go
- gitlab/client_repository_file.go
- gitlab/client_repository_pullrequest.go
- gitlab/integration_test.go
- gitlab/resource_repository.go
- gitlab/resource_teamaccess.go
- gitprovider/client.go
- gitprovider/enums.go
- stash/client.go
- stash/client_repository_pullrequest.go
- stash/client_test.go
- stash/deploy_keys.go
- stash/integration_repositories_user_test.go
- stash/pull_requests.go
- stash/pull_requests_test.go
- stash/resource_organization.go
- stash/resource_pullrequest.go
- validation/multierror.go
This commit adds an `Edit` method to the gitprovider.PullRequestClient interface. Since the APIs for editing PRs/MRs vary widely between providers, an `EditOptions` type is introduced for determining specific fields to be edited.
Currently, only a pull request's title can be edited.
closes #164
> Add API for editing pull requests

- MAINTAINERS
I've been notified that I'm using a different email address in the other Flux projects than in this one. This commit changes that so it's the same across Flux repos now.
> fix my email address

- github/integration_test.go
- github/resource_pullrequest.go
- gitlab/integration_test.go
- gitlab/resource_pullrequest.go
- gitprovider/types_repository.go
- stash/integration_repositories_org_test.go
- stash/integration_repositories_user_test.go
- stash/resource_pullrequest.go
This makes it much easier to identify a PR created from a certain local branch.
> add source branch name to pull request info

- stash/integration_repositories_org_test.go
We have upgraded our bitbucket test instance to v8.7.0 which add stricter controls on SSH keys. The tests case needed to be update to respect RSA keys length.
https://github.com/fluxcd/go-git-providers/actions/runs/3948466900
> fix deploy key test on v8.7.0

- azuredevops/client_repositories.go
- azuredevops/client_repository_branch.go
- azuredevops/client_repository_tree.go
- azuredevops/resource_repository.go
`Repository.Trees().List()`
part of #172
> Feat/azure devops - 

- github/resource_repository.go
- gitlab/client_repository_deploytoken.go
- gitlab/gitlabclient.go
- gitlab/integration_test.go
- gitlab/resource_deploytoken.go
- gitlab/resource_repository.go
- gitlab/util.go
- gitprovider/client.go
- gitprovider/resources.go
- gitprovider/types_repository.go
- gitprovider/types_validation_test.go
- stash/resource_repository.go
This change set implements a `DeployTokenClient` and the associated resource to support GitLab Deploy Tokens in the Flux CLI.
See related discussion here: https://github.com/fluxcd/flux2/discussions/3595
GitLab Issue here: https://gitlab.com/gitlab-org/gitlab/-/issues/392605
Prerequisite for this to merge is a new release from `go-gitlab` and update in this package which includes:
- https://github.com/xanzy/go-gitlab/pull/1662
> Implement client for Deploy Tokens

- go.mod
- go.sum
- stash/auth.go
- stash/client.go
- stash/client_test.go
In version 1.2.4 of logr a [change](https://github.com/go-logr/logr/pull/166) was introduced that significantly changed the assumptions about logr's API, i.e. that `logr.Logger{} != logr.Discard()`. This condition doesn't evaluate to true with 1.2.4, anymore, and the default value of the `logr.Logger` type is now usable as a replacement for `logr.Discard()`.
Therefore we do not need to check if the value has been provided, anymore: If it is not provided, the default one is used which is effectively a discarding logger.
closes #209
> update logr to 1.2.4 and fix Stash client

- .github/workflows/build.yaml
- .github/workflows/e2e-github.yaml
- .github/workflows/e2e-gitlab.yaml
- .github/workflows/e2e-stash.yaml
- .github/workflows/release.yaml
- github/auth.go
- github/client.go
- github/client_organization_teams.go
- github/client_repositories_org.go
- github/client_repository_branch.go
- github/client_repository_commit.go
- github/client_repository_deploykey.go
- github/client_repository_file.go
- github/client_repository_pullrequest.go
- github/example_organization_test.go
- github/example_repository_test.go
- github/githubclient.go
- github/integration_test.go
- github/resource_commit.go
- github/resource_deploykey.go
- github/resource_organization.go
- github/resource_pullrequest.go
- github/resource_repository.go
- github/util.go
- github/util_test.go
- go.mod
- go.sum
If implemented workflows will use `go1.20.x`.
Update of all needed dependencies. There is a breaking change on go-github which introduce its own timeStamp struct.
- "github.com/google/go-github/v52/github"
> Update dependencies and github workflows

- stash/repositories.go
As observed in `fluxcd/pkg` tests:
https://github.com/fluxcd/pkg/actions/runs/5046501353/jobs/9052890218
> stash: avoid panic on err without resp

- .github/workflows/e2e-gitea.yaml
- .github/workflows/e2e-github.yaml
- .github/workflows/e2e-gitlab.yaml
- .github/workflows/e2e-stash.yaml
- README.md
No other Flux project uses Codecov (deliberately so) so this is in alignment with that sentiment.
> Remove code coverage reporting from project

- gitea/client_test.go
This is necessary to get rid of the external dependency on try.gitea.io and instead use the ephemeral instance spun up as part of e2e testing.
It makes us independent of bugs in Gitea that are deployed at try.gitea.io, e.g. https://github.com/go-gitea/gitea/issues/25350.
> Declare Gitea client test e2e

- gitea/client_repositories_org.go
- gitea/client_repositories_user.go
- gitea/client_repository_commit.go
- gitea/integration_repositories_org_test.go
- gitea/integration_repositories_user_test.go
- gitea/integration_suite_test.go
- gitea/resource_repository.go
- gitea/util.go
- github/client_repositories_user.go
- github/integration_test.go
- gitlab/client_repositories_user.go
- gitlab/integration_test.go
- stash/client_repositories_user.go
- stash/integration_repositories_user_test.go
- stash/repositories.go
- GitHub/Gitea/GitLab providers:
The `UserRepositoriesClient.Create` method's `UserRepositoryRef`
parameter contains a `UserLogin` field which is not taken into
account for this call. Instead, the repository is actually created
in the namespace of the user that is tied to the token used by the
respective `gitprovider.Client` implementation.
If a user now passed in a `UserLogin` that is different from the one
derived from the token, the return value of `Create` would still
contain the wrong `UserLogin` passed in to `Create` and methods like
`GetCloneURL` would return the wrong URL.
With this commit, the returned `UserRepository` now points to the
correct owner of the repository.
- Stash/Bitbucket Server:
The Stash provider actually took the field into account and would
fail to create the …
> Return correct repo info after creation

- gitea/integration_repositories_user_test.go
- gitea/integration_suite_test.go
- gitea/resource_commit.go
- gitea/resource_commit_test.go
fix panic when `gitea` commit object contains nil pointers
https://github.com/fluxcd/go-git-providers/actions/runs/5475990179/jobs/9972869429
> fix panic when gitea commit object contains nil pointers

- gitea/client_repositories_user.go
- gitea/integration_repositories_user_test.go
- github/client_repositories_user.go
- github/githubclient.go
- github/integration_test.go
- gitlab/client_repositories_user.go
- gitlab/gitlabclient.go
- gitlab/integration_test.go
- gitprovider/client.go
- gitprovider/errors.go
- stash/client_repositories_user.go
This pull request adds a function to the `UserRepositories` interface called `GetUserLogin`. It gets the current 
authenticated user associated with the token. This function is used when creating user repositories to validate 
that UserLogin. This is required because the Create API doesn't require you to pass a user and giving the wrong UserLogin
successfully creates a repository.
When running `flux bootstrap` with the wrong user (and the repository already exists) returns this confusing error because
ggp tries to create the repository under the authenticated user. 
```
flux bootstrap github --owner=soule --token-auth --repository=fleet-infra --personal
► connecting to github.com
✗ failed to create new Git repository "https://github.com/soule/fleet-infra": multiple errors occurred:
- POST …
```
> Validate user ref when creating user repository

- github/client_repository_file.go
Fix `defer` in for loop.
In Go idioms, "defer" inside a for loop is not good.
```console
$ go test -v -race -count=1 -shuffle=on -run=. ./github
-test.shuffle 1704783961903108000
=== RUN   Test_validateAPIObject
=== RUN   Test_validateAPIObject/no_error_=>_nil
=== RUN   Test_validateAPIObject/one_error_=>_MultiError_&_InvalidServerData
--- PASS: Test_validateAPIObject (0.00s)
--- PASS: Test_validateAPIObject/no_error_=>_nil (0.00s)
--- PASS: Test_validateAPIObject/one_error_=>_MultiError_&_InvalidServerData (0.00s)
=== RUN   Test_allPages
=== RUN   Test_allPages/one_page_only,_no_error
=== RUN   Test_allPages/two_pages,_no_error
=== RUN   Test_allPages/four_pages,_error_at_second
--- PASS: Test_allPages (0.00s)
--- PASS: Test_allPages/one_page_only,_no_error (0.00s)
--- PASS: …
```
> github: fix defer in for loop

- .github/workflows/build.yaml
- .github/workflows/e2e-gitea.yaml
- .github/workflows/e2e-github.yaml
- .github/workflows/e2e-gitlab.yaml
- .github/workflows/e2e-stash.yaml
- .github/workflows/release.yaml
- .github/workflows/scan.yaml
- DEVELOPMENT.md
Part of: https://github.com/fluxcd/flux2/issues/4927
> Build with Go 1.23

- .github/workflows/e2e-gitea.yaml
- .github/workflows/e2e-github.yaml
- .github/workflows/e2e-gitlab.yaml
- .github/workflows/e2e-stash.yaml
Dependabot PRs don't have permission to access certain resources such as repo/org secrets so the e2e tests will always fail on those PRs.
It doesn't make a lot of sense to run e2e tests on dependabot PRs, anyway, as we only let dependabot bump actions which don't have any impact on the functionality of the library.
> Skip running e2e tests on dependabot PRs

- gitlab/auth.go
- gitlab/client.go
- gitlab/client_organization_teams.go
- gitlab/client_repositories_org.go
- gitlab/client_repository_branch.go
- gitlab/client_repository_commit.go
- gitlab/client_repository_deploykey.go
- gitlab/client_repository_deploytoken.go
- gitlab/client_repository_file.go
- gitlab/client_repository_pullrequest.go
- gitlab/client_repository_tree.go
- gitlab/example_organization_test.go
- gitlab/example_repository_test.go
- gitlab/gitlabclient.go
- gitlab/integration_test.go
- gitlab/resource_commit.go
- gitlab/resource_deploykey.go
- gitlab/resource_deploytoken.go
- gitlab/resource_organization.go
- gitlab/resource_pullrequest.go
- gitlab/resource_repository.go
- gitlab/util.go
- gitlab/util_test.go
- go.mod
- go.sum
go-gitlab moves to gitlab.com: https://github.com/xanzy/go-gitlab/issues/2060. The latest releases of https://gitlab.com/gitlab-org/api/client-go require Go 1.23, and I don't want to miss a Go upgrade into this PR.
Somehow tests are failing on my workstation, but it's failing with the same errors without this change. 🤔 Might be something strange in my corporate environment.
````
$ make test
go mod tidy -compat=1.22
go fmt ./...
go vet ./...
go test  -race -coverprofile=coverage.txt -covermode=atomic ./...
?       github.com/fluxcd/go-git-providers/bitbucket    [no test files]
github.com/fluxcd/go-git-providers/gitprovider/cache            coverage: 0.0% of statements
github.com/fluxcd/go-git-providers/gitprovider/testutils                coverage: 0.0% of statements
2024/12/28 13:10:25 …
```
> Migrate to new GitLab client-go

- gitlab/client.go
- gitlab/example_organization_test.go
- gitlab/example_repository_test.go
- gitlab/gitlabclient.go
- gitlab/util.go
This fixes some misleading comments in the GitLab client. The GitHub references are probably copy-pasted from the GitHub client. I am also updating a comment referring to the old GitLab client module replaced in https://github.com/fluxcd/go-git-providers/pull/307.
I should have fixed this in https://github.com/fluxcd/go-git-providers/pull/307, but I noticed this after the PR was merged.
N/A
> Update misleading GitLab client comments

- gitea/client.go
- gitea/example_organization_test.go
- gitea/example_repository_test.go
The Gitea tests were failing because the examples in the `./gitea` package were run against the Gitea instance hosted at gitea.com, which unfortunately isn't compatible with its own SDK:
```
$ curl https://gitea.com/api/v1/version
{"version":"d64e081bf6"}
```
This led to the tests to fail with this error:
```
2025/01/03 14:44:48 failed to create Gitea client: unknown version: d64e081bf6
```
I decided it's not worth it trying to make the tests run against the locally-running e2e instance as these are run as unit tests and the instance might not even be running and would also need to prepared with a repository. Also, the `// Output` comment isn't very flexible and can only contain a static string.
However, to make debugging errors in the client creation easier in the future, I added the …
> Fix Gitea tests
